# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- develop

  # Web app name
  webAppName: 'Testing'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  - task: ArtifactoryConan@1
    inputs:
      conanCommand: 'Add Remote'
      remoteName: 'bandi-cloud'
      artifactoryService: 'bandi-conan-vignesh'
      conanRepo: 'conan-local'
      purgeExistingRemotes: false
- task: ArtifactoryConan@1
  inputs:
    conanCommand: 'Install'
    pathOrReference: './conan/conanfile.txt'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryConan@1
  inputs:
    conanCommand: 'Upload'
    patternOrReference: 'conan upload "*" --all -r bandi-cloud -c'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'